### ISSUE TITLE
Signature expired

### ISSUE THREAD

**Issue by yantakus** [ordenull/wordpress-plugin-cdn-cache-invalidator#1]
Hi. I used the plugin in my local WP instance and everything worked well. When I try to use it in production, it throws an error when I enter credentials: 

```
Signature expired: 20160617T054927Z is now earlier than 20160617T060347Z (20160617T060847Z - 5 min.)
```

Regenerating access and secret keys didn't help. Amazon docs doesn't explain anything, just state this error means my signature is expired (thanks, Cap).

What does it mean?

**Comment by ordenull** [comment]
It seems likely that the date/time on the server might be inaccurate. If you're running in the HVM (Hardware Virtual Machine) mode as opposed to paravirtualized machine, I recommend running a process to keep the server's time in sync. Although each distribution has their own nuances for configuring this there is alot of documentation available if you search for "time synchronization" or "time server."

**Comment by yantakus** [comment]
We set NTP and everything works now. Thanks.
